### ISSUE TITLE
Action started failing today because of empty `output:` entry in `actions.yml`

### ISSUE THREAD

**Issue by alpeb** [devblackops/github-action-psscriptanalyzer#12]
Hi,

The action started failing today, it seems something in Github changed that now it's failing actions with an empty `output:` entry in `actions.yml`:

```
##[error]devblackops/github-action-psscriptanalyzer/v2/action.yml (Line: 30, Col: 9): Unexpected value ''
##[error]devblackops/github-action-psscriptanalyzer/v2/action.yml (Line: 30, Col: 9): Unexpected value ''
##[error]System.ArgumentException: Unexpected type 'NullToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.
```
(taken from this run: https://github.com/alpeb/linkerd2/runs/946382403?check_suite_focus=true )

Is anybody else experiencing the same issue?

Thanks!

**Comment by SleepySysadmin** [comment]
Bump.

I'm getting the same error:

```2020-08-06T14:42:17.2382794Z ##[section]Starting: Request a runner to run this job
2020-08-06T14:42:17.3955013Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2020-08-06T14:42:17.4745437Z Can't find any online and idle self-hosted runner in current repository's organization/enterprise account that matches the required labels: 'ubuntu-latest'
2020-08-06T14:42:17.5899864Z Found online and idle hosted runner in current repository's enterprise account that matches the required labels: 'ubuntu-latest'
2020-08-06T14:42:17.7188012Z ##[section]Finishing: Request a runner to run this job
2020-08-06T14:42:24.3484609Z Current runner version: '2.272.0'
2020-08-06T14:42:24.3516424Z ##[group]Operating System
2020-08-06T14:42:24.3517223Z Ubuntu
2020-08-06T14:42:24.3517484Z 18.04.4
2020-08-06T14:42:24.3517692Z LTS
2020-08-06T14:42:24.3517898Z ##[endgroup]
2020-08-06T14:42:24.3518113Z ##[group]Virtual Environment
2020-08-06T14:42:24.3518302Z Environment: ubuntu-18.04
2020-08-06T14:42:24.3518540Z Version: 20200802.1
2020-08-06T14:42:24.3518858Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200802.1/images/linux/Ubuntu1804-README.md
2020-08-06T14:42:24.3519129Z ##[endgroup]
2020-08-06T14:42:24.3520331Z Prepare workflow directory
2020-08-06T14:42:24.3711632Z Prepare all required actions
2020-08-06T14:42:24.3724851Z Download action repository 'actions/checkout@v2'
2020-08-06T14:42:26.2671073Z Download action repository 'devblackops/github-action-psscriptanalyzer@master'
2020-08-06T14:42:26.6401753Z ##[error]devblackops/github-action-psscriptanalyzer/master/action.yml (Line: 30, Col: 9): Unexpected value ''
2020-08-06T14:42:26.6517537Z ##[error]devblackops/github-action-psscriptanalyzer/master/action.yml (Line: 30, Col: 9): Unexpected value ''
2020-08-06T14:42:26.6519550Z ##[error]System.ArgumentException: Unexpected type 'NullToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
2020-08-06T14:42:26.6541138Z ##[error]Fail to load devblackops/github-action-psscriptanalyzer/master/action.yml
```

**Comment by devblackops** [comment]
`v2.3.0` has been published with these fixes in. I've also updated pwsh to `7.0.3` and `PSScriptAnalyzer` to `1.19.1`.
